name: msvc

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - 'schemas/**'
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - 'schemas/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_arch: [x64]
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      shell: bash -el {0}
      run: >
        cmake -S . -B build -G Ninja 
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build
      shell: bash -el {0}
      run: cmake --build build --target plugify --config ${{ matrix.build_type }} --parallel

#    - name: Test
#      shell: bash -el {0}
#      working-directory: build
#      run: ctest --build-config ${{ matrix.build_type }}
